"""init

Revision ID: eb7559ae70c7
Revises: def1af1fa244
Create Date: 2021-09-04 04:47:49.929937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7559ae70c7'
down_revision = 'def1af1fa244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datas_id'), 'datas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datas_id'), table_name='datas')
    op.drop_table('datas')
    # ### end Alembic commands ###
